name: Deploy game on Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: C/C++ dev tools
      run: |
        sudo echo 'deb http://dk.archive.ubuntu.com/ubuntu/ xenial main' >> /etc/apt/sources.list
        sudo echo 'deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe' >> /etc/apt/sources.list
        sudo apt update
        sudo apt-get install build-essential gcc-5-multilib g++-5-multilib

    - name: Create makefile
      run: |
        sudo chmod +x ./createall
        sudo chmod +x ./devtools/gendbg.sh
        sudo chmod +x ./devtools/bin/vpc
        sudo chmod +x ./devtools/bin/vpc_linux
        sudo chmod +x ./devtools/bin/linux/ccache
        ./createall

    - name: Build
      run: make -f msc.mak

    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        name: Linux Binaries
        path: |
          build/*.so
